version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/japanese-comics-notice-admin
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/codedeploy_ApplicationStart.sh
      timeout: 180
  ApplicationStop:
    - location: scripts/codedeploy_ApplicationStop.sh
      timeout: 180
  ValidateService:
    - location: scripts/codedeploy_clear_file.sh
      timeout: 180
      runas: root